# Laravel Cloud Configuration

# Build assets during deployment
build:
  - npm ci
  - npm run build

# Post-deployment commands
deploy:
  - php artisan migrate --force
  - php artisan config:cache
  - php artisan route:cache
  - php artisan view:cache
  - php artisan storage:link

