# Laravel Cloud Configuration
# Updated: Force cache clear and use committed assets

# Build assets during deployment (SKIP - usando assets commiteados)
build:
  - echo "Using pre-built assets from repository"

# Post-deployment commands
deploy:
  - php artisan migrate --force
  - php artisan cache:clear
  - php artisan config:clear
  - php artisan view:clear
  - php artisan config:cache
  - php artisan route:cache
  - php artisan view:cache
  - php artisan storage:link

