# Laravel Cloud Configuration
# Updated: Force cache clear and use committed assets

# Build commands - OVERRIDE panel settings
build:
  - composer install --no-dev --optimize-autoloader
  - echo "✅ Using pre-built assets from repository - skipping npm build"

# Post-deployment commands
deploy:
  - php artisan migrate --force
  - rm -f public/storage
  - php artisan storage:link --force
  - php artisan announcements:migrate-banners
  - php artisan cache:clear
  - php artisan config:clear
  - php artisan view:clear
  - php artisan config:cache
  - php artisan route:cache
  - php artisan view:cache

